language: node_js

node_js:
  - "node"
  - "8"
  - "6"
  - "4"

os:
  - linux
  - osx

env:
  - WEBPACK_VERSION=1
  - WEBPACK_VERSION=2
  - WEBPACK_VERSION=3
  - WEBPACK_VERSION=4

matrix:
  exclude:
  - node_js: "4"
    env: WEBPACK_VERSION=4

install:
  - npm install
  - npm rm webpack
  - npm install webpack@$WEBPACK_VERSION || true

branches:
  only:
    - master
